config/routes.rb
RPWeb::Application.routes.draw do

  resources :careers

  resources :characters do
    resources :character_competences
    member do
      post 'add_talent'
      delete 'rm_talent'
    end
  end

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"

  devise_for :users

end

app/models/career.rb
class Career < ActiveRecord::Base

  #Descriptions
  attr_accessible :name, :description
  #Attributes
  attr_accessible :skills_desc, :talents_desc, :trappings_desc, :entry_desc, :exit_desc
  #Profile
  attr_accessible :ws, :bs, :s, :t, :ag, :int, :wp, :fel, :a, :w, :mag, :tb, :m, :ip, :fp 

  has_many :career_entry
  has_many :next_career, :through => :career_entry
end

app/controllers/careers_controller.rb
class CareersController < ApplicationController
  # GET /careers
  # GET /careers.json
  def index
    @careers = Career.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @careers }
    end
  end

  # GET /careers/1
  # GET /careers/1.json
  def show
    @career = Career.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @career }
    end
  end

  # GET /careers/new
  # GET /careers/new.json
  def new
    @career = Career.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @career }
    end
  end

  # GET /careers/1/edit
  def edit
    @career = Career.find(params[:id])
  end

  # POST /careers
  # POST /careers.json
  def create
    @career = Career.new(params[:career])

    respond_to do |format|
      if @career.save
        format.html { redirect_to new_career_path, notice: 'Career was successfully created.' }
        format.json { render json: @career, status: :created, location: @career }
      else
        format.html { render action: "new" }
        format.json { render json: @career.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /careers/1
  # PUT /careers/1.json
  def update
    @career = Career.find(params[:id])

    respond_to do |format|
      if @career.update_attributes(params[:career])
        format.html { redirect_to @career, notice: 'Career was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @career.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /careers/1
  # DELETE /careers/1.json
  def destroy
    @career = Career.find(params[:id])
    @career.destroy

    respond_to do |format|
      format.html { redirect_to careers_url }
      format.json { head :no_content }
    end
  end
end

app/views/careers/_form.html.erb
<%= form_for(@career) do |f| %>
  <% if @career.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@career.errors.count, "error") %> prohibited this career from being saved:</h2>

      <ul>
      <% @career.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.label :name %>
    <%= f.text_field :name %> <br/>
    
    <table id='prof_main'>
      <tr>
	<th>CC</th>
	<th>CT</th>
	<th>F</th>
	<th>E</th>
	<th>Ag</th>
	<th>Int</th>
	<th>FM</th>
	<th>Soc</th>
      </tr>
      <tr>
	<td><%= f.text_field :ws %></td>
	<td><%= f.text_field :bs %></td>
	<td><%= f.text_field :s %></td>
	<td><%= f.text_field :t %></td>
	<td><%= f.text_field :ag %></td>
	<td><%= f.text_field :int %></td>
	<td><%= f.text_field :wp %></td>
	<td><%= f.text_field :fel %></td>
      </tr>
    </table>

    <table id='prof_adv'>
      <tr>
	<th>A</th>
	<th>B</th>
	<th>M</th>
	<th>BE</th>
	<th>BF</th>
	<th>M</th>
	<th>PF</th>
	<th>PF</th>
      </tr>
      <tr>
	<td><%= f.text_field :a %></td>
	<td><%= f.text_field :w %></td>
	<td><%= f.text_field :sb %></td>
	<td><%= f.text_field :tb %></td>
	<td><%= f.text_field :m %></td>
	<td><%= f.text_field :mag %></td>
	<td><%= f.text_field :ip %></td>
	<td><%= f.text_field :fp %></td>
      </tr>
    </table>
  
    <%= f.label :skills_desc %>
    <%= f.text_field :skills_desc %> <br/>
    <%= f.label :talents_desc %>
    <%= f.text_field :talents_desc %> <br/>
    <%= f.label :trappings_desc %>
    <%= f.text_field :trappings_desc %> <br/>
    <%= f.label :entry_desc %>
    <%= f.text_field :entry_desc %> <br/>
    <%= f.label :exit_desc %>
    <%= f.text_field :exit_desc %> <br/>
    <%= f.label :description %>
    <%= f.text_area :description %> <br/>
    <%= f.submit %>
  </div>
<% end %>

app/views/careers/edit.html.erb
<h1>Editing career</h1>

<%= render 'form' %>

<%= link_to 'Show', @career %> |
<%= link_to 'Back', careers_path %>

app/views/careers/index.html.erb
<h1>Listing careers</h1>

<ul>
<% @careers.each do |career| %>
  <li>
    <%= career.name %>
    <%= link_to 'Show', career %>
    <%= link_to 'Edit', edit_career_path(career) %>
    <%= link_to 'Destroy', career, method: :delete, data: { confirm: 'Are you sure?' } %>
  </li>
<% end %>
</ul>
<br />

<%= link_to 'New Career', new_career_path %>

app/views/careers/new.html.erb
<h1>New career</h1>

<%= render 'form' %>

<%= link_to 'Back', careers_path %>

app/views/careers/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @career.name %></h1>

<div id='content'>
  <div id='attributes'>
    <div id="profile" class="char_blck">

      <h2>Profile</h2>

      <table id='prof_main'>
	<tr>
	  <th>CC</th>
	  <th>CT</th>
	  <th>F</th>
	  <th>E</th>
	  <th>Ag</th>
	  <th>Int</th>
	  <th>FM</th>
	  <th>Soc</th>
	</tr>
	<tr>
	  <td><%= @career.ws %></td>
	  <td><%= @career.bs %></td>
	  <td><%= @career.s %></td>
	  <td><%= @career.t %></td>
	  <td><%= @career.ag %></td>
	  <td><%= @career.int %></td>
	  <td><%= @career.wp %></td>
	  <td><%= @career.fel %></td>
	</tr>
      </table>

      <table id='prof_adv'>
	<tr>
	  <th>A</th>
	  <th>B</th>
	  <th>Mag</th>
	  <th>BE</th>
	  <th>BF</th>
	  <th>M</th>
	  <th>PF</th>
	  <th>PF</th>	
	</tr>
	  <tr>
	  <td><%= @career.a %></td>
	  <td><%= @career.w %></td>
	  <td><%= @career.mag %></td>
	  <td><%= @career.tb %></td>
	  <td><%= @career.sb %></td>
	  <td><%= @career.m %></td>
	  <td><%= @career.ip %></td>
	  <td><%= @career.fp %></td>
      </tr></table>
      </div>

      <b>Competences: </b><%= @career.skills_desc %><br/>
      <b>Talents: </b><%= @career.talents_desc %><br/>
      <b>Equipement: </b><%= @career.trappings_desc %><br/>
      <b>Carrière d'accès: </b><%= @career.entry_desc %><br/>
      <b>Débouché: </b><%= @career.exit_desc %><br/>
    </div>

    <div id='description'>
      <h2>Descritpion</h2>
	<%= simple_format(@career.description) %>	
    </div>
<div>

<%= link_to 'Edit', edit_career_path(@career) %> |
<%= link_to 'Back', careers_path %>