config/routes.rb
RPWeb::Application.routes.draw do

  resources :careers

  resources :characters do
    resources :character_competences
    member do
      post 'add_talent'
      delete 'rm_talent'
    end
  end

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"

  devise_for :users

end

app/models/character.rb
class Character < ActiveRecord::Base
  belongs_to :user
  belongs_to :race
  belongs_to :career

  has_many :character_competences
  has_many :competences, :through => :character_competences
  has_and_belongs_to_many :talents

  before_create :profile_creation

  #Character
  attr_accessible :name, :race_id, :career_id
  #Details
  attr_accessible :age, :gender, :eye_color, :weight, :height, :star_sign, :number_of_sibling, :birthplace, :distinguishing_marks
  #Base Profile
  attr_accessible :base_weapon_skill, :base_balistic_skill, :base_strength, :base_toughness, 
  :base_agility, :base_intelligence, :base_will_power, :base_fellowship, 
  :base_attacks, :base_wounds, :base_mouvement, :base_insanity_points, :base_fate_points,
  :base_magic
  #Creation description
  attr_accessible :status 

  def base_strength_bonus
    if self.base_strength.nil?
      return 0
    else
      return self.base_strength / 10
    end
  end
  
  def base_toughness_bonus
    if self.base_toughness.nil?
      return 0
    else
      return self.base_toughness / 10
    end
  end
  
  def get_competence_bonus(competence)
    idx= self.character_competences.index { |o| o.competence_id == competence.id }
    bonus=self.character_competences[idx].bonus
    return bonus
  end

  def get_chara_comp(competence)
    if self.competences.include?(competence)
      idx= self.character_competences.index { |o| o.competence_id == competence.id }
      chara_comp=self.character_competences[idx]
      return chara_comp
    end
  end

  def add_competence(competence)
   if self.competences.include? competence
	idx= self.character_competences.index { |o| o.competence_id == competence.id }
	if self.character_competences[idx].bonus <= 10
		self.character_competences[idx].bonus += 10
	end
   else
      self.competences << competence
   end
  end

  private
  def profile_creation
    if (self.race_id == 0 or self.race_id >= 5)
      raise(InvalidRaceError, "This race is not handeled")
    end
    #t[race_id+][base profile id]
    t = [
          [ 30 , 20 , 20 , 30 , 10 , 20 , 20 , 10 , 1 , 3 , 0 , 0] ,
          [ 20 , 30 , 20 , 20 , 30 , 20 , 20 , 20 , 1 , 5 , 0 , 0] ,
          [ 10 , 30 , 10 , 10 , 30 , 20 , 20 , 30 , 1 , 4 , 0 , 0] ,
          [ 20 , 20 , 20 , 20 , 20 , 20 , 20 , 20 , 1 , 4 , 0 , 0] ,
        ]

    self.base_weapon_skill   = t[self.race_id-1][0] + Dice.throw + Dice.throw
    self.base_balistic_skill = t[self.race_id-1][1] + Dice.throw + Dice.throw
    self.base_strength       = t[self.race_id-1][2] + Dice.throw + Dice.throw
    self.base_toughness      = t[self.race_id-1][3] + Dice.throw + Dice.throw
    self.base_agility        = t[self.race_id-1][4] + Dice.throw + Dice.throw
    self.base_intelligence   = t[self.race_id-1][5] + Dice.throw + Dice.throw
    self.base_will_power     = t[self.race_id-1][6] + Dice.throw + Dice.throw
    self.base_fellowship     = t[self.race_id-1][7] + Dice.throw + Dice.throw
    self.base_attacks        = t[self.race_id-1][8]
    self.base_mouvement      = t[self.race_id-1][9]
    self.base_magic          = t[self.race_id-1][10]
    self.base_insanity_points= t[self.race_id-1][11]

    self.base_wounds         = starting_wound(Dice.throw)
    self.base_fate_points    = starting_fp(Dice.throw)
  end

  def starting_wound(dice10)
    #t[:race_id-1][:dice_part]
    t = [
          [ 11 , 12 , 13 , 14 ] ,
          [  9 , 10 , 11 , 12 ] ,
          [  8 ,  9 , 10 , 11 ] ,
          [ 10 , 11 , 12 , 13 ]
        ]
    if dice10 >= 1 and dice10 <= 3
      tmp = 0
    elsif dice10 >= 4 and dice10 <= 6
      tmp = 1
    elsif dice10 >= 7 and dice10 <= 9 
      tmp = 2
    elsif dice10 == 10
      tmp = 3
    else
      raise("Invalid dice result")
    end
    return t[self.race_id-1][tmp]
  end

  def starting_fp(dice10)
    #t[:race_id-1][:dice_part]
    t = [
          [ 1 , 2 , 3 ] ,
          [ 1 , 2 , 2 ] ,
          [ 2 , 2 , 3 ] ,
          [ 2 , 3 , 3 ]
        ]
    if dice10 >= 1 and dice10 <= 4
      tmp = 0
    elsif dice10 >= 5 and dice10 <= 7
      tmp = 1
    elsif dice10 >= 8 and dice10 <= 10
      tmp = 2
   else
      raise("Invalid dice result")
    end
    return t[self.race_id-1][tmp]
  end



end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController

require 'dice'

  before_filter :authenticate_user!, :except => [:index, :show]

  # GET /characters
  # GET /characters.json
  def index
    @characters = Character.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @characters }
    end
  end

  # GET /characters/1
  # GET /characters/1.json
  def show
    @character = Character.find(params[:id])
    @char_comp = @character.character_competences
    @competences = Competence.where(:base => true)
    @chara_adv_comp = @char_comp.select { |x| ! x.competence.base }

    @char_talents = @character.talents

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @character }
    end
  end

  # GET /characters/new
  # GET /characters/new.json
  def new
    @race = Race.all
    @career = Career.where("access like ?", "Basic%")
    @character = Character.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @character }
    end
  end

  # GET /characters/1/edit
  def edit
    @race = Race.all
    @character = Character.find(params[:id])
    @char_comp = @character.character_competences
    @competences = Competence.where(:base => true)
    @chara_adv_comp = @char_comp.select { |x| ! x.competence.base }
    @career = Career.all

    @char_talents = @character.talents
  end

  # POST /characters/1/add_talent
  def add_talent
    @character = Character.find(params[:id])
    talent=Talent.find(params[:talent][:talent_id])
    respond_to do |format|
      if @character.talents << talent
	format.html { redirect_to edit_character_path(@character), notice: 'Talent successfully added.' }
        format.json { render json: @character, status: :created, location: @character }
      else
        format.html { render action: "new" }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def rm_talent
    @character = Character.find(params[:id])
    talent = Talent.find(params[:talent_id])
    respond_to do |format|
      if @character.talents.delete(talent)
	format.html { redirect_to edit_character_path(@character), notice: 'Talent successfully removed.' }
        format.json { render json: @character, status: :created, location: @character }
      else
        format.html { render action: "new" }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # POST /characters
  # POST /characters.json
  def create
    @character = Character.new(params[:character])
    @character.user_id = current_user.id
    @character.status = 0

    respond_to do |format|
      if @character.save
        format.html { redirect_to @character, notice: 'Character successuly created.' }
        format.json { render json: @character, status: :created, location: @character }
      else
        format.html { render action: "new" }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /characters/1
  # PUT /characters/1.json
  def update
    @character = Character.find(params[:id])
    if ( @character.status == 0 )
      add_native_attr
    end
    respond_to do |format|
      if @character.save
        format.html { redirect_to @character, notice: 'Character was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /characters/1
  # DELETE /characters/1.json
  def destroy
    @character = Character.find(params[:id])
    @character.destroy

    respond_to do |format|
      format.html { redirect_to characters_url }
      format.json { head :no_content }
    end
  end
  
  private
  
  def add_native_attr
    #Check no cheat
    if ( ! params[:character][:native_comp].length == @character.race.native_skills_array.length )
      respond_to do |format|
	format.html { redirect_to edit_character_path(@character), notice: 'Wrong number of skills' }
	format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
    params[:character][:native_comp].each do |c|
      comp = Competence.find( c[:competence_id] )
      @character.add_competence(comp)
    end
    @character.status = 1
  end
end

app/views/characters/_competences_list.html.erb
<div id="competence_base" class="char_blck">
<h2>Competence de base</h2>
  <ul>
  <% @competences.each do |comp| %>
    <% if cc=@character.get_chara_comp(comp) %>
      <li class="have">
	<%= comp.name %>
	<%= "(+#{cc.bonus}%)" %>
	<span class="dropt" title="Help">?
	<span style="width:500px;"><%= comp.description %></span>
	</span>
      </li>
    <% else %>
      <li class="no_have">
	<%= comp.name %>
	<span class="dropt" title="Help">?
	<span style="width:500px;"><%= comp.description %></span>
	</span>
      </li>
    <% end %>
  <% end %>
  </ul>
</div>

<div id="competence_adv" class="char_blck">
<h2>Competence avancée</h2>
  <ul>
    <% @chara_adv_comp.each do |cc| %>
      <li>
	<%= cc.competence.name %>
	<%= cc.bonus %>
	<span class="dropt" title="Help">?
	<span style="width:500px;"><%= cc.competence.description %></span>
	</span>
      </li>
    <% end %>
  </ul>
</div>

app/views/characters/_competences_list_edit.html.erb
<div id="competence_base" class="char_blck">
<h2>Competence de base</h2>
  <ul>
  <% @competences.each do |comp| %>
    <% if cc=@character.get_chara_comp(comp) %>
      <li class="have">
	<%= comp.name %>
	<%= "(+#{cc.bonus}%)" %>
	<%= link_to 'Destroy', [cc.character, cc], method: :delete, data: { confirm: 'Are you sure?' } %>
      </li>
    <% else %>
      <li class="no_have">
	<%= comp.name %>
      </li>
    <% end %>
  <% end %>
  </ul>
</div>

<div id="competence_adv" class="char_blck">
<h2>Competence avancée</h2>
  <ul>
    <% @chara_adv_comp.each do |cc| %>
      <li>
	<%= cc.competence.name %>
	<%= link_to 'Destroy', [cc.character, cc], method: :delete, data: { confirm: 'Are you sure?' } %>
      </li>
    <% end %>
  </ul>
</div>


<%= form_for([@character,@character.character_competences.build]) do |f| %>
  <%= f.collection_select(:competence_id, Competence.all, :id, :name ) %><br />
  <%= f.submit %>
<% end %>

app/views/characters/_first_update.html.erb
<%= form_for(@character) do |f| %>
  <div id='col1'>
   <div id="profile" class="char_blck">
      <h2>Misericorde de Shallya</h2>
      <table id='prof_main'>
        <tr>
          <th>CC</th>
          <th>CT</th>
          <th>F</th>
          <th>E</th>
          <th>Ag</th>
          <th>Int</th>
          <th>FM</th>
          <th>Soc</th>
        </tr>
        <tr>
          <td><%= @character.base_weapon_skill %></td>
          <td><%= @character.base_balistic_skill %></td>
          <td><%= @character.base_strength %></td>
          <td><%= @character.base_toughness %></td>
          <td><%= @character.base_agility %></td>
          <td><%= @character.base_intelligence %></td>
          <td><%= @character.base_will_power %></td>
          <td><%= @character.base_fellowship %></td>
        </tr>
        <tr>
          <td><%= radio_button_tag(:shallya, :ws) %></td>
          <td><%= radio_button_tag(:shallya, :bs) %></td>
          <td><%= radio_button_tag(:shallya, :s ) %></td>
          <td><%= radio_button_tag(:shallya, :t ) %></td>
          <td><%= radio_button_tag(:shallya, :ag) %></td>
          <td><%= radio_button_tag(:shallya, :int)%></td>
          <td><%= radio_button_tag(:shallya, :wp) %></td>
          <td><%= radio_button_tag(:shallya, :fel)%></td>
        </tr>
      </table>

      <table id='prof_adv'>
        <tr>
          <th>A</th>
          <th>B</th>
          <th>Mag</th>
          <th>BE</th>
          <th>BF</th>
          <th>M</th>
          <th>PF</th>
          <th>PF</th>
        </tr>
        <tr>
          <td><%= @character.base_attacks %></td>
          <td><%= @character.base_wounds %></td>
          <td><%= @character.base_magic %></td>
          <td><%= @character.base_toughness_bonus %></td>
          <td><%= @character.base_strength_bonus %></td>
          <td><%= @character.base_mouvement %></td>
          <td><%= @character.base_insanity_points %></td>
          <td><%= @character.base_fate_points %></td>
        </tr>
      </table>

    </div>

  </div>
  <div id='col2'>
    <% if @nskl_choice.length > 0 %>
      <div id="competence_choice" class="char_blck">
        <h2>Choix de Compétences</h2>
        <ul>
          <% skills = @nskl_choice.each do |grp| %>
	          <%= fields_for "native_comp[]", CharacterCompetence.new do |t| %>
              <li><%= t.collection_select(:competence_id, grp, :id, :name ) %></li>
            <% end %>
          <% end %>
        </ul>
      </div>
    <% end %>
    <% if @ntal_choice.length > 0 %>
      <div id="talent_choice" class="char_blck">
      <h2>Choix de Talents</h2>
      <ul>
        <% skills = @ntal_choice.each do |grp| %>
          <%= fields_for "native_tal[]", CharacterTalent.new do |t| %>
            <li><%= t.collection_select(:talent_id, grp, :id, :name ) %></li>
          <% end %>
        <% end %>
      </ul>
    <% end %>
  </div>
<%= f.submit %>
<% end %>
</div>

app/views/characters/_form.html.erb
<div id="character" class="char_blck">
<h2>Personnage</h2>
<%= form_for(@character) do |f| %>
  <% if @character.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@character.errors.count, "error") %> prohibited this character from being saved:</h2>

      <ul>
      <% @character.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :race %>
    <%= f.collection_select(:race_id, @race, :id, :name ) %>
  </div>

   <div class="field">
    <%= f.label :career %>
    <%= f.collection_select(:career_id, @career, :id, :name ) %>
  </div>
 </div> 
<div id="chara_details" class="char_blck">
  <h2>Details Personnels</h2>
  <%= f.label :age,'Age' %><%= f.text_field :age %></br>
  <%= f.label :gender,'Gendre' %><%= f.text_field :gender %></br>
  <%= f.label :eye_color,'Yeux' %><%= f.text_field :eye_color %></br>
  <%= f.label :weight,'Poid' %><%= f.text_field :weight %></br>
  <%= f.label :height,'Taille' %><%= f.text_field :height %></br>
  <%= f.label :star_sign,'Signe' %><%= f.text_field :star_sign %></br>
  <%= f.label :number_of_sibling,'Frère/Soeurs' %><%= f.text_field :number_of_sibling %></br>
  <%= f.label :birthplace,'Lieu de naissance' %><br/><%= f.text_field :birthplace %></br>
  <%= f.label :distinguishing_marks,'Signe distinctif' %><br/><%= f.text_field :distinguishing_marks %></br>
</div>
<div id="profile" class="char_blck">
  <h2>Profile</h2>
  <table id='prof_main'>
    <tr>
      <th>CC</th>
      <th>CT</th>
      <th>F</th>
      <th>E</th>
      <th>Ag</th>
      <th>Int</th>
      <th>FM</th>
      <th>Soc</th>
    </tr>
    <tr>
      <td><%= f.text_field :base_weapon_skill %></td>
      <td><%= f.text_field :base_balistic_skill %></td>
      <td><%= f.text_field :base_strength %></td>
      <td><%= f.text_field :base_toughness %></td>
      <td><%= f.text_field :base_agility %></td>
      <td><%= f.text_field :base_intelligence %></td>
      <td><%= f.text_field :base_will_power %></td>
      <td><%= f.text_field :base_fellowship %></td>
    </tr>
  </table>

  <table id='prof_adv'>
    <tr>
      <th>A</th>
      <th>B</th>
      <th>Mag</th>
      <th>BE</th>
      <th>BF</th>
      <th>M</th>
      <th>PF</th>
      <th>PF</th>
    </tr>
    <tr>
      <td><%= f.text_field :base_attacks %></td>
      <td><%= f.text_field :base_wounds %></td>
      <td><%= f.text_field :base_magic %></td>
      <td></td>
      <td></td>
      <td><%= f.text_field :base_mouvement %></td>
      <td><%= f.text_field :base_insanity_points %></td>
      <td><%= f.text_field :base_fate_points %></td>
    </tr>
  </table>

</div>
  
  
  
 <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/characters/_profile.html.erb
<div id="profile" class="char_blck">

  <h2>Profile</h2>

  <table id='prof_main'>
    <tr>
      <th>CC</th>
      <th>CT</th>
      <th>F</th>
      <th>E</th>
      <th>Ag</th>
      <th>Int</th>
      <th>FM</th>
      <th>Soc</th>
    </tr>
    <tr>
      <td><%= @character.base_weapon_skill %></td>
      <td><%= @character.base_balistic_skill %></td>
      <td><%= @character.base_strength %></td>
      <td><%= @character.base_toughness %></td>
      <td><%= @character.base_agility %></td>
      <td><%= @character.base_intelligence %></td>
      <td><%= @character.base_will_power %></td>
      <td><%= @character.base_fellowship %></td>
    </tr>
    <tr>
      <td><%= @character.career.ws %></td>
      <td><%= @character.career.bs %></td>
      <td><%= @character.career.s %></td>
      <td><%= @character.career.t %></td>
      <td><%= @character.career.ag %></td>
      <td><%= @character.career.int %></td>
      <td><%= @character.career.wp %></td>
      <td><%= @character.career.fel %></td>
    </tr>
    <tr>
      <td><%= @character.ws %></td>
      <td><%= @character.bs %></td>
      <td><%= @character.s %></td>
      <td><%= @character.t %></td>
      <td><%= @character.ag %></td>
      <td><%= @character.int %></td>
      <td><%= @character.wp %></td>
      <td><%= @character.fel %></td>
    </tr>

  </table>

  <table id='prof_adv'>
    <tr>
      <th>A</th>
      <th>B</th>
      <th>Mag</th>
      <th>BE</th>
      <th>BF</th>
      <th>M</th>
      <th>PF</th>
      <th>PF</th>
    </tr>
    <tr>
      <td><%= @character.base_attacks %></td>
      <td><%= @character.base_wounds %></td>
      <td><%= @character.base_magic %></td>
      <td><%= @character.base_toughness_bonus %></td>
      <td><%= @character.base_strength_bonus %></td>
      <td><%= @character.base_mouvement %></td>
      <td><%= @character.base_insanity_points %></td>
      <td><%= @character.base_fate_points %></td>
    </tr>
    <tr>
      <td><%= @character.career.a %></td>
      <td><%= @character.career.w %></td>
      <td><%= @character.career.mag %></td>
      <td><%= @character.career.tb %></td>
      <td><%= @character.career.sb %></td>
      <td><%= @character.career.m %></td>
      <td><%= @character.career.ip %></td>
      <td><%= @character.career.fp %></td>
    </tr>
    <tr>
      <td><%= @character.a %></td>
      <td><%= @character.w %></td>
      <td><%= @character.mag %></td>
      <td><%= @character.tb %></td>
      <td><%= @character.sb %></td>
      <td><%= @character.m %></td>
      <td><%= @character.ip %></td>
      <td><%= @character.fp %></td>
    </tr>
  </table>
</div>

app/views/characters/_talents_list.html.erb
 
<div id='char_talent' class="char_blck">
<h2>Talents</h2>
<ul>
<% @char_talents.each do |t| %>
  <li>
    <%= t.name  %>
    <span class="dropt" title="Help">?
    <span style="width:500px;"><%= t.description %></span>
    </span>
  </li>
<% end %>
</ul>
</div>

app/views/characters/_talents_list_edit.html.erb
 
<div id='char_talent' class="char_blck">
<h2>Talents</h2>
<ul>
<% @char_talents.each do |t| %>
  <li>
    <%= t.name  %>
    <span class="dropt" title="Title for the pop-up">?
    <span style="width:500px;"><%= t.description %></span>
    </span>
    <%= link_to 'Destroy', "/characters/#{@character.id}/rm_talent?talent_id=#{t.id}" , method: :delete, data: { confirm: 'Are you sure?' } %>
  </li>
<% end %>
</ul>
</div>

<%= form_tag "/characters/#{@character.id}/add_talent" do %>
  <%= collection_select(:talent,:talent_id, Talent.all, :id, :name ) %><br />
  <%= submit_tag %>
<% end %>

app/views/characters/edit.html.erb
<% if @character.status == 0 %>
  <%= form_for(@character) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %> <br/>
      <% skills = @character.race.native_skills_array.each do |grp| %>
	<%= f.fields_for "native_comp[]", CharacterCompetence.new do |t| %>
	  <% if grp.length == 1 %>
	    <%= t.hidden_field :competence_id, :value => grp.first.id %>
	    <%= grp.first.name %><br/>
	  <% else %>
	    <%= t.label :competence_id %>
	    <%= t.collection_select(:competence_id, grp, :id, :name ) %><br/>
	  <% end %>
	<% end %> 
      <% end %>
    <%= f.submit %>
  <% end %>
<% else %>

<h1>Editing character</h1>

<div id='content'>
  <div id='col1'>

    <%= render 'form' %>

  </div>
  <div id='col2'>
    <%= render 'competences_list_edit' %>
    <%= render 'talents_list_edit' %>
  </div>

<% end %>

<%= link_to 'Show', @character %> |
<%= link_to 'Back', characters_path %>

app/views/characters/index.html.erb
<h1>Listing characters</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Race</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @characters.each do |character| %>
  <tr>
    <td><%= character.name %></td>
    <td><%= character.race.name %></td>
    <td><%= character.user.login %></td>
    <td><%= link_to 'Show', character %></td>
    <td><%= link_to 'Edit', edit_character_path(character) %></td>
    <td><%= link_to 'Destroy', character, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Character', new_character_path %>

app/views/characters/new.html.erb
<h1>New character</h1>

<%= render 'form' %>

<%= link_to 'Back', characters_path %>

app/views/characters/show.html.erb
<div id='content'>
  <div id='col1'>
    <div id="character" class="char_blck">
      <h2>Character</h2>
      <b>Name:</b>
      <%= @character.name %><br/>
      <b>Race:</b>
      <%= @character.race.name %><br/>
      <b>User:</b>
      <%= @character.user.login %><br/>
      <b>User:</b>
      <%= @character.career.name %><br/>
    </div>
    <div id="chara_details" class="char_blck">
      <h2>Details Personnels</h2>
      Age : <%= @character.age %></br>
      Gender : <%= @character.gender %></br>
      Yeux : <%= @character.eye_color %></br>
      Poid : <%= @character.weight %></br>
      Taille : <%= @character.height %></br>
      Signe : <%= @character.star_sign %></br>
      Frère/Soeurs : <%= @character.number_of_sibling %></br>
      Lieu de naissance : <%= @character.birthplace %></br>
      Signe distinctif : <%= @character.distinguishing_marks %></br>
    </div>

    <%= render 'profile' %>

  </div>
  <div id='col2'>
  
    <%= render 'competences_list' %>

    <%= render 'talents_list' %>

  </div>
</div>

<%= link_to 'Edit', edit_character_path(@character) %> |
<%= link_to 'Back', characters_path %>